### ISSUE TITLE
Can you update the code to 2.1.0?

### ISSUE THREAD

**Issue by nicobelist** [balanceofprobability/decaptcha#10]
the will resolver some errors like has error on debian about lib cuda that the tensorflow not seam to have you can use that to automate the update https://www.tensorflow.org/guide/migrate thanks Bro.
also has this code that seam not make the samething but using tensorflow 2 https://github.com/ozankaraali/yolov3-recaptcha i dont know if is the right section but if isn't let me know thanks.

**Comment by balanceofprobability** [comment]
Hi @nicobelist, Tensorflow 2.1.0 introduced a breaking change that affected the ImageAI library, hence why it's currently pinned in `setup.py` - see [build #236](https://travis-ci.com/balanceofprobability/decaptcha/builds/145009791). I haven't had time to investigate it, but if you want to look into it, feel free to submit a PR to the [imageai](https://imageai.readthedocs.io/en/latest/) repo.

**Comment by balanceofprobability** [comment]
Closing for now, since it's really an [ImageAI](https://github.com/OlafenwaMoses/ImageAI) issue.

**Comment by balanceofprobability** [comment]
Closing for now, since it's really an [ImageAI](https://github.com/OlafenwaMoses/ImageAI) issue.
