### ISSUE TITLE
The installation via pip fails in Windows

### ISSUE THREAD

**Issue by Snickbrack** [balanceofprobability/decaptcha#6]
Hi,

i have tried the following:
pip install decaptcha

But I ended up with an error:

>   Running setup.py install for tesserocr ... error
>     Complete output from command C:\Users\Himken\Anaconda3\envs\test\python.exe
> -u -c "import setuptools, tokenize;__file__='C:\\Users\\Himken\\AppData\\Local\\
> Temp\\pip-install-msktmjqo\\tesserocr\\setup.py';f=getattr(tokenize, 'open', ope
> n)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __
> file__, 'exec'))" install --record C:\Users\Himken\AppData\Local\Temp\pip-record
> -9tvc3jos\install-record.txt --single-version-externally-managed --compile:
>     Failed to extract tesseract version from executable: [WinError 2] Das System
>  kann die angegebene Datei nicht finden
>     Supporting tesseract v3.04.00
>     Building with configs: {'cython_compile_time_env': {'TESSERACT_VERSION': 505
> 93792}, 'libraries': ['tesseract', 'lept']}
>     running install
>     running build
>     running build_ext
>     building 'tesserocr' extension
>     creating build
>     creating build\temp.win-amd64-3.5
>     creating build\temp.win-amd64-3.5\Release
>     C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
> /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Himken\Anaconda3\envs\test\includ
> e -IC:\Users\Himken\Anaconda3\envs\test\include "-IC:\Program Files (x86)\Micros
> oft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual St
> udio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\1
> 0.0.10586.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\
> um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared" "-IC:
> \Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um" "-IC:\Program File
> s (x86)\Windows Kits\10\include\10.0.10586.0\winrt" /EHsc /Tptesserocr.cpp /Fobu
> ild\temp.win-amd64-3.5\Release\tesserocr.obj
>     tesserocr.cpp
>     tesserocr.cpp(634): fatal error C1083: Cannot open include file: 'leptonica/
> allheaders.h': No such file or directory
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
> IN\\x86_amd64\\cl.exe' failed with exit status 2
> 
>     ----------------------------------------
> Command "C:\Users\Himken\Anaconda3\envs\test\python.exe -u -c "import setuptools
> , tokenize;__file__='C:\\Users\\Himken\\AppData\\Local\\Temp\\pip-install-msktmj
> qo\\tesserocr\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read
> ().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" instal
> l --record C:\path\of\my\pc\AppData\Local\Temp\pip-record-9tvc3jos\install-record
> .txt --single-version-externally-managed --compile" failed with error code 1 in
> C:\path\of\my\pc\AppData\Local\Temp\pip-install-msktmjqo\tesserocr\

**Comment by balanceofprobability** [comment]
@Snickbrack looks like a tessorocr issue. It wasn't designed to run on Windows https://github.com/sirfz/tesserocr/issues/19

**Comment by balanceofprobability** [comment]
Closing issue, since Windows support is outside scope for this project
